model_params:
  im_channels : 3
  im_height : 128
  im_width: 128
  down_channels : [32, 32, 64, 128, 256, 512]
  mid_channels : [512, 512, 512, 512, 256]
  down_sample : [True, False, True, False, True]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  epochs: 5000
  modelpath: 'models'
  checkpoint_latest: 'latest.pth'
  checkpoint_epoch: 5
  lr: 0.0003
  num_training_samples: 5000

noise_params:
  beta_min: 0.0001
  beta_max: 0.02
  timesteps: 700

data_params:
  batch: 8
  datapath: 'data/celeb-dataset/img_align_celeba/img_align_celeba'
  trainpath: 'data/train'


  